### ISSUE TITLE
Seeded Users following themselves instead of others

### ISSUE THREAD

**Issue by austin-espinal** [Connor2h/A-T-Anime#28]
Acceptance criteria: 

- Seeded users don't follow themselves
- Seeded users follow random users

**Comment by Connor2h** [comment]
Fixed in [Merge pull request](https://github.com/Connor2h/A-T-Anime/commit/ab34feca5bf5805914f1723ba980a9836bea67ae) https://github.com/Connor2h/A-T-Anime/pull/30
